<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/MS.Microservice.Core/MS.Microservice.Core.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="MS.Microservice.Persistence.EFCore.Tests" /></ItemGroup>
</Project>
