<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../MS.Microservice.Core/MS.Microservice.Core.csproj" />
  </ItemGroup>
</Project>
