apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  container:
  - name: main
    image: busybox
    command: ["sleep", "999999"]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 15m
        memory: 4Mi
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath:  metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath:  metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath:  status.IP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath:  spec.nodeName
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath:  spec.serviceAccountName
    - name: CONTAINER_CPU_REQUEST_MILLICORES
      valueFrom:
        resourceFieldRef:
          resource: requests.cpu
          divisor: 1m # 设定的CPU请求的基数为 1m（即 1 millicore，千分之一核 CPU）
    - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
      valueFrom:
        resourceFieldRef:
          resource: limits.memory # 设定内存的使用限制为 1Ki，取得是变量 spec.container 节点里定义的变量
          divisor: 1Ki