<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <EnableOfficeDiagnostics Condition="'$(EnableOfficeDiagnostics)' == ''">false</EnableOfficeDiagnostics>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>
  <PropertyGroup Condition="'$(EnableOfficeDiagnostics)' == 'true'">
    <DefineConstants>$(DefineConstants);MS_Microservice_DIAGNOSTICS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MS.Microservice.Excel.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NPOI" />
  </ItemGroup>
</Project>
