<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>MS.Microservice.Lab-74ee2e9f-dc95-41ad-8c56-e571635f784f</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MS.Microservice.Web\MS.Microservice.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\src\MS.Microservice.Web\appsettings.json" Link="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
