// <auto-generated />
using System;
using MS.Microservice.Reference.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MS.Microservice.Reference.Persistence.Migrations.SelfManaged
{
    [DbContext(typeof(SelfManagedReferenceDbContext))]
    [Migration("20260923112723_AddHttpIdempotency")]
    partial class AddHttpIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reference")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MS.Microservice.Idempotency.EFCore.IdempotencyRecord", b =>
                {
                    b.Property<string>("ScopeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Body")
                        .HasColumnType("bytea");

                    b.Property<long?>("CompletedAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("ScopeHash", "KeyHash");

                    b.HasIndex("ExpiresAtUtcTicks");

                    b.ToTable("HttpIdempotency", "reference");
                });

            modelBuilder.Entity("MS.Microservice.Messaging.SelfManaged.InboxEntry", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LockToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("Inbox", "messaging");
                });

            modelBuilder.Entity("MS.Microservice.Messaging.SelfManaged.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LockToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("Outbox", "messaging");
                });

            modelBuilder.Entity("MS.Microservice.Reference.Domain.ProfileAuditEntry", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ProfileId", "ProfileVersion", "Consumer")
                        .IsUnique();

                    b.ToTable("ProfileAudit", "reference");
                });

            modelBuilder.Entity("MS.Microservice.Reference.Domain.ProfileRole", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ProfileId", "Name");

                    b.ToTable("ProfileRoles", "reference");
                });

            modelBuilder.Entity("MS.Microservice.Reference.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("UserProfiles", "reference");
                });

            modelBuilder.Entity("MS.Microservice.Reference.Domain.ProfileRole", b =>
                {
                    b.HasOne("MS.Microservice.Reference.Domain.UserProfile", null)
                        .WithMany("Roles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MS.Microservice.Reference.Domain.UserProfile", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
