<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MS.Microservice.Audio.Tests" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="NAudio.Lame" />
  </ItemGroup>
</Project>
