using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MS.Microservice.Excel.Generator;

[Generator]
public sealed class ExcelSourceGenerator : IIncrementalGenerator
{
    private const string Marker = "MS.Microservice.Excel.Aot.ExcelSerializableAttribute";
    private const string ColumnMarker = "MS.Microservice.Excel.Aot.ExcelColumnAttribute";
    private const string Api = "global::MS.Microservice.Excel.Aot.";
    private static readonly DiagnosticDescriptor Invalid = new("EXCEL001", "Invalid Excel mapping", "{0}", "Excel", DiagnosticSeverity.Error, true);
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(Marker,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntax, _) => Generate(syntax));
        context.RegisterSourceOutput(sources, static (production, result) =>
        {
            if (result.Error is not null) production.ReportDiagnostic(result.Error);
            else if (result.Source is not null) production.AddSource(result.Name!, SourceText.From(result.Source, Encoding.UTF8));
        });
    }

    private static (string? Name, string? Source, Diagnostic? Error) Generate(GeneratorAttributeSyntaxContext syntax)
    {
        var context = (INamedTypeSymbol)syntax.TargetSymbol;
        var registrations = context.GetAttributes().Where(a => a.AttributeClass?.ToDisplayString() == Marker).ToArray();
        // A context can put its attributes on several partial declarations. Emit it only once.
        var first = registrations[0].ApplicationSyntaxReference;
        if (first is not null && (first.SyntaxTree != syntax.TargetNode.SyntaxTree || !syntax.TargetNode.Span.Contains(first.Span))) return default;
        (string?, string?, Diagnostic?) Fail(string message, ISymbol? member = null)
            => (null, null, Diagnostic.Create(Invalid, (member ?? context).Locations.FirstOrDefault(l => l.IsInSource) ?? context.Locations.FirstOrDefault(l => l.IsInSource), message));
        if (!context.IsStatic || context.TypeParameters.Length != 0)
            return Fail("Excel context must be a non-generic static partial class.");
        var containers = new Stack<INamedTypeSymbol>();
        for (var type = context; type is not null; type = type.ContainingType)
        {
            if (type.TypeParameters.Length != 0 || type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is not ClassDeclarationSyntax declaration
                    || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
                return Fail("Excel context and its containing classes must be non-generic partial classes.");
            containers.Push(type);
        }
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (!context.ContainingNamespace.IsGlobalNamespace) code.Append("namespace ").Append(context.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        foreach (var type in containers)
            code.Append(type.IsStatic ? "static partial class @" : "partial class @").Append(type.Name).AppendLine(" {");
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var registration in registrations)
        {
            if (registration.ConstructorArguments[0].Value is not INamedTypeSymbol model || model.TypeKind != TypeKind.Class
                || model.IsUnboundGenericType || !syntax.SemanticModel.Compilation.IsSymbolAccessibleWithin(model, context))
                return Fail("Excel model must be an accessible, closed class type.");
            var name = Argument<string>(registration, "Name") ?? model.Name;
            if ((!SyntaxFacts.IsValidIdentifier(name) && SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None) || !names.Add(name) || context.GetMembers(name).Length != 0)
                return Fail($"Generated map name '{name}' is invalid or duplicated. Specify a unique Name.");
            var modelName = model.ToDisplayString(TypeFormat);
            var factoryName = Argument<string>(registration, "Factory");
            string factory;
            if (factoryName is not null)
            {
                if (!context.GetMembers(factoryName).OfType<IMethodSymbol>().Any(m => m.IsStatic && m.Arity == 0 && m.Parameters.Length == 0
                    && SymbolEqualityComparer.Default.Equals(m.ReturnType, model) && m.ReturnNullableAnnotation != NullableAnnotation.Annotated))
                    return Fail($"Factory '{factoryName}' must be a static parameterless method on this context returning {modelName}.");
                factory = "@" + factoryName + "()";
            }
            else
            {
                if (model.IsAbstract || !model.InstanceConstructors.Any(c => c.Parameters.Length == 0 && syntax.SemanticModel.Compilation.IsSymbolAccessibleWithin(c, context))
                    || Properties(model).Any(p => p.IsRequired))
                    return Fail($"Model '{modelName}' needs an accessible parameterless constructor or an explicit Factory.", model);
                factory = "new " + modelName + "()";
            }
            code.Append("public static ").Append(Api).Append("ExcelModelMap<").Append(modelName).Append("> @").Append(name)
                .Append(" { get; } = new(static () => ").Append(factory);
            var columns = new HashSet<string>(StringComparer.Ordinal);
            foreach (var property in Properties(model).OrderBy(p => Argument<int?>(Column(p), "Order") ?? int.MaxValue))
            {
                var attribute = Column(property);
                if (Argument<bool?>(attribute, "Ignore") == true) continue;
                if (!syntax.SemanticModel.Compilation.IsSymbolAccessibleWithin(property.GetMethod!, context))
                    return Fail($"Getter '{property.Name}' is not accessible from the Excel context.", property);
                var title = (Argument<string>(attribute, "Name") ?? (attribute?.ConstructorArguments.FirstOrDefault().Value as string) ?? property.Name).Trim();
                if (title.Length == 0 || !columns.Add(title)) return Fail($"Column name '{title}' is empty or duplicated.", property);
                var valueType = property.Type;
                var optional = valueType is INamedTypeSymbol nullable && nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                var underlying = optional ? ((INamedTypeSymbol)valueType).TypeArguments[0] : valueType;
                var converter = Argument<INamedTypeSymbol>(attribute, "Converter");
                if (converter is not null)
                {
                    if (!syntax.SemanticModel.Compilation.IsSymbolAccessibleWithin(converter, context)
                        || !converter.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == "MS.Microservice.Excel.Aot.IExcelCellConverter<T>"
                            && SymbolEqualityComparer.IncludeNullability.Equals(i.TypeArguments[0], valueType)))
                        return Fail($"Converter for '{property.Name}' must implement IExcelCellConverter<{valueType.ToDisplayString(TypeFormat)}> and be accessible.", property);
                }
                else if (!Supported(underlying)) return Fail($"Property '{property.Name}' has unsupported type '{valueType}'. Ignore it or specify a typed Converter.", property);
                code.AppendLine(",").Append("new ").Append(Api).Append("ExcelColumn<").Append(modelName).Append(">(").Append(SymbolDisplay.FormatLiteral(title, true)).AppendLine(", static (model, row, column, dateStyle) => {")
                    .Append("var value = model.@").Append(property.Name).AppendLine(";");
                var needsNullCheck = optional || valueType.IsReferenceType;
                if (needsNullCheck) code.AppendLine("if (value is null) return;");
                code.AppendLine("var cell = row.GetCell(column) ?? row.CreateCell(column);");
                var value = optional && converter is null ? "value.Value" : "value";
                if (converter is not null) code.Append(Api).Append("ExcelCellConverter.Write<").Append(valueType.ToDisplayString(TypeFormat)).Append(", ").Append(converter.ToDisplayString(TypeFormat)).AppendLine(">(cell, value, dateStyle);");
                else Write(code, underlying, value);
                code.Append("}, ");
                if (property.SetMethod is null || property.SetMethod.DeclaredAccessibility != Accessibility.Public || property.SetMethod.IsInitOnly
                    || !syntax.SemanticModel.Compilation.IsSymbolAccessibleWithin(property.SetMethod, context)) code.Append("null)");
                else
                {
                    code.AppendLine("static (model, reader) => {");
                    if (converter is not null)
                        code.Append("if (").Append(Api).Append("ExcelCellConverter.TryRead<").Append(valueType.ToDisplayString(TypeFormat)).Append(", ").Append(converter.ToDisplayString(TypeFormat)).Append(">(reader, out var value)) model.@").Append(property.Name).AppendLine(" = value;");
                    else Read(code, underlying, property.Name);
                    code.Append("})");
                }
            }
            if (columns.Count == 0) return Fail($"Model '{modelName}' has no eligible columns.", model);
            code.AppendLine(");");
        }
        foreach (var _ in containers) code.AppendLine("}");
        if (!context.ContainingNamespace.IsGlobalNamespace) code.AppendLine("}");
        return (context.ToDisplayString() + ".Excel.g.cs", code.ToString(), null);
    }

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol model)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var type = model; type is not null; type = type.BaseType)
            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
                if (seen.Add(property.Name) && !property.IsStatic && !property.IsIndexer && property.GetMethod?.DeclaredAccessibility == Accessibility.Public)
                    yield return property;
    }
    private static AttributeData? Column(IPropertySymbol property)
        => property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ColumnMarker);
    private static T? Argument<T>(AttributeData? attribute, string name)
    {
        if (attribute is not null)
            foreach (var argument in attribute.NamedArguments)
                if (argument.Key == name && argument.Value.Value is T value) return value;
        return default;
    }
    private static bool Numeric(ITypeSymbol type) => type.SpecialType is SpecialType.System_Byte or SpecialType.System_SByte
        or SpecialType.System_Int16 or SpecialType.System_UInt16 or SpecialType.System_Int32 or SpecialType.System_UInt32
        or SpecialType.System_Int64 or SpecialType.System_UInt64 or SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal;
    private static bool Supported(ITypeSymbol type) => Numeric(type) || type.SpecialType is SpecialType.System_String or SpecialType.System_Boolean
        || type.TypeKind == TypeKind.Enum || type.ToDisplayString() is "System.DateTime" or "System.Guid";
    private static string Styles(ITypeSymbol type) => "global::System.Globalization.NumberStyles." + (type.SpecialType switch
    {
        SpecialType.System_Single or SpecialType.System_Double => "Float | global::System.Globalization.NumberStyles.AllowThousands",
        SpecialType.System_Decimal => "Number",
        _ => "Integer"
    });
    private static void Write(StringBuilder code, ITypeSymbol type, string value)
    {
        if (type.TypeKind == TypeKind.Enum) code.Append(Api).Append("ExcelEnumWriter.Write(cell, ").Append(value).AppendLine(");");
        else if (type.ToDisplayString() == "System.DateTime")
            code.Append("cell.SetCellValue(").Append(value).AppendLine("); if (dateStyle is not null) cell.CellStyle = dateStyle;");
        else if (type.ToDisplayString() == "System.Guid") code.Append("cell.SetCellValue(").Append(value).AppendLine(".ToString());");
        else code.Append("cell.SetCellValue(").Append(Numeric(type) ? "(double)" : "").Append(value).AppendLine(");");
    }
    private static void Read(StringBuilder code, ITypeSymbol type, string property)
    {
        if (type.TypeKind == TypeKind.Enum)
        {
            var underlying = ((INamedTypeSymbol)type).EnumUnderlyingType!;
            code.Append("if (reader.TryReadNumber<").Append(underlying.ToDisplayString(TypeFormat)).Append(">(").Append(Styles(underlying))
                .Append(", out var number)) model.@").Append(property).Append(" = (").Append(type.ToDisplayString(TypeFormat)).AppendLine(")number;")
                .Append("else if (global::System.Enum.TryParse<").Append(type.ToDisplayString(TypeFormat)).Append(">(reader.GetText(), true, out var value)) model.@")
                .Append(property).AppendLine(" = value;");
            return;
        }
        code.Append("if (reader.");
        if (Numeric(type)) code.Append("TryReadNumber<").Append(type.ToDisplayString(TypeFormat)).Append(">(").Append(Styles(type)).Append(", ");
        else code.Append(type.SpecialType switch
        {
            SpecialType.System_String => "TryReadString(",
            SpecialType.System_Boolean => "TryReadBoolean(",
            _ => type.ToDisplayString() == "System.Guid" ? "TryReadGuid(" : "TryReadDateTime("
        });
        code.Append("out var value)) model.@").Append(property).AppendLine(" = value;");
    }
}
