<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MS.Microservice.Reference.Domain/MS.Microservice.Reference.Domain.csproj" />
    <ProjectReference Include="../../../src/MS.Microservice.Core/MS.Microservice.Core.csproj" />
    <ProjectReference Include="../../../MS.Microservice.Messaging/src/MS.Microservice.Messaging.Abstractions/MS.Microservice.Messaging.Abstractions.csproj" />
  </ItemGroup>
</Project>
