apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects
spec:
  hard: # 硬件资源：命名空间下最多创建10个pod，5个rc，10个secret，10个configmap，4个pvc
    pods: 10
    replicationcontrollers: 5
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 4
    # 最多创建5个service，其中最多1个loadbalancer类型和2个nodeport类型
    services: 5
    services.loadbalancers: 1
    services.nodeports: 2
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2
