apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodepet
spec:
  serviceName: nodepet
  replicas: 2
  selector:
    matchLabels:
      app: nodepet # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: nodepet
    spec:
      containers:
      - name: nodepet
        image: marsonshine/node-pet
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /var/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Mi
      accessModes:
      - ReadWriteOnce