<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>

  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SqlSugarCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/MS.Microservice.Core/MS.Microservice.Core.csproj" />
  </ItemGroup>
</Project>
